version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lookup_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
